import { useMemo, useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpFromLine, Bot, Check, Clock3, Cpu, MapPin, Radio, Route, Server, Smartphone } from "lucide-react";
import { agents } from "../data";
import { Heading, Panel, SectionTitle, Tag } from "../components/Primitives";

const tone={Working:"blue","Needs review":"amber",Idle:"neutral",Migrated:"green",Canary:"purple",Monitoring:"green",Watching:"green"};
export default function AgentsPage(){
 const [selected,setSelected]=useState(agents[3]);const [filter,setFilter]=useState("All");
 const visible=useMemo(()=>agents.filter(a=>filter==="All"||a.mode===filter.toUpperCase()),[filter]);
 return <div className="page-wrap"><Heading eyebrow="Fleet operations" title="Agent status" subtitle="Health, workload, and mobility paths across the T2D-MAS fleet." action={<span className="fleet-health"><i className="online-dot"/>11 / 11 healthy</span>}/>
  <div className="agent-layout"><Panel className="agent-list-panel"><div className="panel-head"><SectionTitle title="Agent fleet" detail="11 registered agents"/><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter agents"><option>All</option><option>Static</option><option>Mobile</option></select></div><div className="agent-list">{visible.map(agent=><button className={`agent-row ${selected.id===agent.id?"active":""}`} key={agent.id} onClick={()=>setSelected(agent)}><span className={`agent-avatar role-${agent.role.toLowerCase()}`}>{agent.mode==="MOBILE"?<Smartphone size={17}/>:<Bot size={17}/>}</span><span className="agent-main"><span><b>{agent.id}</b><small className={`mode ${agent.mode.toLowerCase()}`}>{agent.mode==="MOBILE"?"✈ Mobile":"⌖ Static"}</small></span><small>{agent.task}</small><span className="agent-row-meta"><small><Server size={10}/>{agent.host}</small><small><Cpu size={10}/>{agent.load}%</small><small><Clock3 size={10}/>{agent.beat}</small></span></span><Tag tone={tone[agent.status]}>{agent.status}</Tag></button>)}</div></Panel>
   <div className="agent-side"><Panel className="agent-profile"><div className="profile-head"><span className={`agent-avatar large role-${selected.role.toLowerCase()}`}>{selected.mode==="MOBILE"?<Smartphone size={20}/>:<Bot size={20}/>}</span><div><small className="eyebrow">{selected.role} · {selected.mode.toLowerCase()} agent</small><h2>{selected.id}</h2><span>{selected.task}</span></div><Tag tone={tone[selected.status]}>{selected.status}</Tag></div><div className="agent-specs"><div><small><Server size={12}/>Current host</small><b>{selected.host}</b></div><div><small><Clock3 size={12}/>Heartbeat</small><b className="healthy">{selected.beat} <Check size={12}/></b></div><div><small><Radio size={12}/>Version</small><b>v0.8.4 · policy 12</b></div></div><div className="load-row"><span><Cpu size={13}/>Workload</span><b>{selected.load}%</b></div><div className="load-track"><i style={{width:`${selected.load}%`}}/></div></Panel>
    <Panel className="mobility-card"><div className="panel-head"><div><small className="eyebrow">Execution context</small><h3>{selected.mode==="MOBILE"?"Mobile execution path":"Static execution"}</h3></div><span className={`mode ${selected.mode.toLowerCase()}`}>{selected.mode==="MOBILE"?"✈ Code to data":"⌖ Data via API"}</span></div><div className="route" aria-label={`Route ${selected.route?.join(" to ")||selected.host}`}>
     {(selected.route||[selected.host]).map((node,i)=><span className="route-step" key={`${node}-${i}`}><i>{i===0?<MapPin size={13}/>:<Server size={13}/>}</i><small>{node}</small>{i<(selected.route||[]).length-1&&<b/>}</span>)}
    </div>{selected.mode==="MOBILE"?<div className="transfer"><div><small><ArrowUpFromLine size={12}/>Bytes sent</small><b>{selected.bytes}</b><span>signed code + state</span></div><div><small><ArrowDownToLine size={12}/>Bytes returned</small><b>{selected.id==="Scout-Log"?"12 MB":"2.1 MB"}</b><span>aggregate features only</span></div></div>:<div className="static-note"><Route size={15}/>This agent reads remote resources through approved APIs.</div>}<div className="privacy-note"><Check size={12}/>Raw production data stays on-node; only allowlisted aggregate features return.</div></Panel>
    <Panel className="activity-card"><SectionTitle title="Recent activity" detail="Latest agent events"/>{[["Now",`${selected.id} heartbeat received`],["2m ago",selected.mode==="MOBILE"?"Signed bundle verified at target node":"Policy context refreshed"],["8m ago","Action appended to audit log"]].map(([time,text])=><div className="activity-row" key={text}><i><Activity size={12}/></i><span>{text}</span><small>{time}</small></div>)}</Panel>
   </div>
  </div>
 </div>;
}
