import { useMemo, useState } from "react";
import { Check, Clock3, ExternalLink, FileSearch, MessageSquareWarning, ShieldAlert, ShieldCheck, X } from "lucide-react";
import { approvals } from "../data";
import { Heading, Panel, SectionTitle, Severity, Tag } from "../components/Primitives";

const waitMinutes=(s)=>{const h=Number(s.match(/(\\d+)h/)?.[1]||0),m=Number(s.match(/(\\d+)m/)?.[1]||0);return h*60+m;};
export default function ApprovalsPage({onNavigate}){
 const [items,setItems]=useState(approvals),[selectedId,setSelectedId]=useState(approvals[0]?.id),[reject,setReject]=useState(null),[reason,setReason]=useState(""),[notice,setNotice]=useState("");
 const ordered=useMemo(()=>[...items].sort((a,b)=>b.risk*waitMinutes(b.waiting)-a.risk*waitMinutes(a.waiting)),[items]);
 const selected=items.find(x=>x.id===selectedId);
 async function decide(item,approved,note=""){
  let backendSaved=false;
  try { const response=await fetch(`/api/tickets/${item.ticket}/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approver:"course-reviewer",approved,reason:note})});if(!response.ok)throw new Error("Approval is not queued in FastAPI");if(approved){const resumed=await fetch(`/api/tickets/${item.ticket}/resume`,{method:"POST"});if(!resumed.ok)throw new Error("Pipeline could not resume")}backendSaved=true; }
  catch { /* Keep the seeded inbox usable when its demo ticket is not in the backend queue. */ }
  setItems(current=>current.filter(x=>x.id!==item.id));setSelectedId(ordered.find(x=>x.id!==item.id)?.id);setReject(null);setReason("");setNotice(backendSaved?(approved?`${item.ticket} approved and returned to the pipeline.`:`${item.ticket} rejected; the reason was recorded.`):`Demo only: ${item.ticket} changed locally; this seeded request was not queued in FastAPI.`);setTimeout(()=>setNotice(""),5000);
 }
 return <div className="page-wrap"><Heading eyebrow="Human governance" title="Approval inbox" subtitle="Review escalations ordered by risk and wait time. High-impact actions stay paused here." action={<span className="approval-count"><ShieldAlert size={15}/>{items.length} decisions waiting</span>}/>
 {notice&&<div className="toast" role="status"><Check size={14}/>{notice}</div>}
 <div className="approval-layout"><Panel className="approval-list"><div className="panel-head"><SectionTitle title="Needs your decision" detail="Sorted by risk × wait time"/><select aria-label="Filter severity"><option>All severities</option><option>Critical</option><option>High</option></select></div>{ordered.map(item=><button className={`approval-item ${selectedId===item.id?"active":""}`} key={item.id} onClick={()=>setSelectedId(item.id)}><span className="approval-top"><Severity value={item.severity}/><b><i/>Risk {item.risk.toFixed(2)}</b></span><strong>{item.title}</strong><small>{item.ticket} · {item.agent}</small><span className="approval-bottom"><span><Clock3 size={12}/>{item.waiting} waiting</span><small>{item.id}</small></span></button>)}{!items.length&&<div className="approval-clear"><ShieldCheck size={24}/><b>Inbox clear</b><span>New escalations will appear here.</span></div>}</Panel>
 {selected?<Panel className="approval-detail"><div className="detail-top"><div><small className="eyebrow">Review request · {selected.id}</small><Severity value={selected.severity}/></div><span className="detail-risk"><i/>Risk {selected.risk.toFixed(2)}</span></div><h2>{selected.title}</h2><div className="detail-meta"><span>{selected.ticket}</span><span>Raised by {selected.agent}</span><span><Clock3 size={12}/>{selected.waiting}</span></div>
 <div className="approval-reason"><MessageSquareWarning size={16}/><div><b>Why this needs review</b><p>{selected.why}</p></div></div><div className="confidence-grid"><div><small>MODEL CONFIDENCE</small><b>{Math.round(selected.confidence*100)}<i>%</i></b><span>Threshold τ = 70%</span></div><div><small>ESTIMATED ACTION RISK</small><b>{selected.risk.toFixed(2)}</b><span>Max allowed 0.60</span></div></div>
 <a href="#trace" className="evidence-link" onClick={e=>{e.preventDefault();onNavigate("trace")}}><i><FileSearch size={16}/></i><span><small>EVIDENCE ATTACHED</small><b>{selected.evidence}</b><em>Open decision trace for context</em></span><ExternalLink size={14}/></a><div className="decision-actions"><button className="button approve" onClick={()=>decide(selected,true)}><Check size={14}/>Approve decision</button><button className="button reject" onClick={()=>{setReject(selected);setReason("")}}><X size={14}/>Reject with reason</button></div><p className="audit-promise"><ShieldCheck size={12}/>Your choice and reviewer identity append to the audit trail.</p>
 </Panel>:<Panel className="approval-clear"><ShieldCheck size={25}/><b>Select a review request</b><span>Inspect the evidence and policy context before deciding.</span></Panel>}</div>
 {reject&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setReject(null)}><section className="reject-modal" role="dialog" aria-modal="true" aria-labelledby="reject-title"><button className="modal-x" onClick={()=>setReject(null)} aria-label="Close"><X size={17}/></button><span className="modal-symbol"><MessageSquareWarning size={18}/></span><small className="eyebrow">Reviewer decision · {reject.ticket}</small><h2 id="reject-title">Reject this request?</h2><p>Give the owning agent a reason so it can correct the proposal. This note is saved in the audit log.</p><label htmlFor="reject-reason">Reason <i>Required</i></label><textarea id="reject-reason" rows="4" maxLength="500" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what should change before this can proceed…" autoFocus/><div className="modal-actions"><small>{reason.trim().length}/500</small><button className="button secondary" onClick={()=>setReject(null)}>Cancel</button><button className="button danger" disabled={!reason.trim()} onClick={()=>decide(reject,false,reason.trim())}>Confirm rejection</button></div></section></div>}
 </div>
}
