import { useMemo,useState } from "react";
import { Activity,ArrowDownRight,BarChart3,Download,GitBranch,GitPullRequest,Timer,TrendingDown,UsersRound,Workflow } from "lucide-react";
import { CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { trend } from "../data";
import { Heading,Metric,Panel,SectionTitle } from "../components/Primitives";
const dora=[
 ["Deployment frequency","8.6","/ week","+1.4","High performer",GitPullRequest],
 ["Lead time for changes","3h 42m","","−18%","Ticket to production",Timer],
 ["Change failure rate","4.1","%","−1.2 pts","Target below 10%",TrendingDown],
 ["Failed deploy recovery","26","min","−8 min","Mean time to restore",Activity],
 ["Rework rate","7.8","%","+0.6 pts","Requires follow-up",GitBranch],
];
const agentStats=[["Triage accuracy","96.2%","+2.4 pts",Activity],["Duplicate recall@10","91.4%","+1.8 pts",GitBranch],["Token cost / ticket","$0.14","−$0.03",BarChart3],["Network / investigation","84 MB","−98.9% mobile",Workflow],["Human override rate","6.8%","−1.1 pts",UsersRound]];
export default function PerformancePage(){
 const [mode,setMode]=useState("mobile"),[period,setPeriod]=useState("30 days");const data=useMemo(()=>period==="30 days"?trend:trend.slice(-7),[period]);
 const mobile=mode==="mobile",seconds=mobile?27:655,bytes=mobile?84:8190;
 function exportCsv(){const rows=[["day","deployments","lead_time_index","change_failure_index"],...data.map(p=>[p.day,p.deploys,p.lead.toFixed(2),p.failure.toFixed(2)])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="t2d-mas-performance.csv";link.click();URL.revokeObjectURL(url)}
 return <div className="page-wrap"><Heading eyebrow="Reliability & flow · 30 day view" title="Performance report" subtitle="Delivery outcomes alongside agent quality, cost, and governance signals." action={<button className="button primary" onClick={exportCsv}><Download size={15}/>Export CSV</button>}/>
  <div className="report-section-head"><SectionTitle title="DORA metrics" detail="Five delivery and operational health measures"/><small>Sep 1 – Sep 30, 2026</small></div><div className="metric-grid metric-5">{dora.map(([label,value,unit,change,note,icon],i)=><Metric key={label} label={label} value={<>{value}<small>{unit}</small></>} change={change} note={note} icon={icon} good={i!==4}/>)}</div>
  <div className="report-grid"><Panel className="chart-panel"><div className="panel-head"><SectionTitle title="Delivery trend" detail="Daily deploys and normalized delivery indicators"/><select value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Select report period"><option>30 days</option><option>7 days</option></select></div><div className="chart-legend"><span><i className="c-deploy"/>Deployments / day</span><span><i className="c-lead"/>Lead time index</span><span><i className="c-failure"/>Failure index</span></div><div className="chart" role="img" aria-label={`Line chart showing deployment, lead time, and failure indices for the last ${period}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:12,left:-18,bottom:0}}><CartesianGrid stroke="var(--grid)" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:"var(--muted)",fontSize:10}} interval={period==="30 days"?4:0}/><YAxis tickLine={false} axisLine={false} tick={{fill:"var(--muted)",fontSize:10}}/><Tooltip contentStyle={{background:"var(--raised)",border:"1px solid var(--line)",borderRadius:10,color:"var(--ink)"}}/><Line type="monotone" dataKey="deploys" name="Deployments" stroke="#39b994" strokeWidth={2.5} dot={false} activeDot={{r:4}}/><Line type="monotone" dataKey="lead" name="Lead time index" stroke="#8c7cf5" strokeWidth={2} dot={false} activeDot={{r:4}}/><Line type="monotone" dataKey="failure" name="Failure index" stroke="#e5a15a" strokeWidth={2} dot={false} activeDot={{r:4}}/></LineChart></ResponsiveContainer></div><p className="chart-note">Deterministic course demo data. CSV export contains the currently selected date range.</p></Panel>
  <Panel className="compare-panel"><div className="compare-title"><div><small className="eyebrow">Same ticket · TCK-1042</small><h2>Static vs. mobile</h2><p>Compare the investigation under the same incident window.</p></div><span><Workflow size={16}/></span></div><div className="toggle" role="group" aria-label="Execution mode"><button className={!mobile?"selected":""} onClick={()=>setMode("static")}>⌖ Static</button><button className={mobile?"selected":""} onClick={()=>setMode("mobile")}>✈ Mobile</button></div><div className="compare-numbers"><div><small>Elapsed time</small><b>{seconds}<i> sec</i></b></div><div><small>Network transfer</small><b>{bytes.toLocaleString()}<i> MB</i></b></div></div><div className="compare-result"><ArrowDownRight size={14}/><span><b>{mobile?`${(655/27).toFixed(0)}× faster · ${(100*(1-84/8190)).toFixed(1)}% fewer bytes`:"Reference baseline"}</b><small>{mobile?"Scout-Log · six production nodes":"Static pull · same incident window"}</small></span></div><div className="compare-bars">{[["Elapsed",mobile?"27s":"10m 55s",mobile?"8%":"100%"],["Network",mobile?"84 MB":"8.19 GB",mobile?"8%":"100%"]].map(([label,val,width])=><div key={label}><small>{label}</small><span><i style={{width,background:mobile?"#39b994":"#dda35c"}}/></span><b>{val}</b></div>)}</div><p className="assumption">Assumptions: 6 nodes · 1,365 MB logs/node · 12 MB bundle + 2 MB aggregate/node.</p></Panel></div>
  <Panel className="agent-metrics-panel"><div className="panel-head"><SectionTitle title="Agent system metrics" detail="Quality and governance signals · 30 day window"/><small>Seeded demo data · reproducible</small></div><div className="agent-stats">{agentStats.map(([label,value,change,Icon],i)=><div className="agent-stat" key={label}><span className={`agent-stat-icon stat-${i}`}><Icon size={15}/></span><small>{label}</small><b>{value}</b><em><ArrowDownRight size={12}/>{change}</em></div>)}</div></Panel>
 </div>
}
