import { useState } from "react";
import { ChevronDown, ChevronRight, FileText, Fingerprint, ShieldAlert, ShieldCheck } from "lucide-react";
import { trace } from "../data";
import { Heading, Panel, SectionTitle, Severity, Tag } from "../components/Primitives";

function exportTrace(){const file=new Blob([JSON.stringify(trace,null,2)],{type:"application/json"});const url=URL.createObjectURL(file);const link=document.createElement("a");link.href=url;link.download="t2d-decision-trace.json";link.click();URL.revokeObjectURL(url)}
export default function TracePage(){const [open,setOpen]=useState("20:25:00");return <div className="page-wrap"><Heading eyebrow="Governance · decision provenance" title="Decision trace" subtitle="Inspect how an agent reached a decision, which policy applied, and what a reviewer approved." action={<button className="button secondary" onClick={exportTrace}><Fingerprint size={15}/>Export trace</button>}/>
 <Panel className="incident-summary"><span className="incident-icon"><ShieldAlert size={17}/></span><div><small className="eyebrow">Selected incident</small><b>TCK-1042 · Checkout crash during flash sale</b><span>Payments API · Android 14 · 14 Sep 2026, 20:05 WIB</span></div><p>6 events <i/> 3 agents <i/> <strong><ShieldAlert size={12}/> 1 human checkpoint</strong></p></Panel>
 <div className="trace-layout"><Panel className="timeline-panel"><div className="panel-head"><SectionTitle title="Decision timeline" detail="Evidence links to its originating artifact."/><small>14 Sep · WIB</small></div><div className="timeline">{trace.map((item,index)=>{const expanded=open===item.time;const escalated=item.gate==="Escalated";return <article className="trace-row" key={item.time}><div className="trace-rail"><span className={escalated?"alert-marker":"trace-marker"}>{escalated?<ShieldAlert size={14}/>:String(index+1).padStart(2,"0")}</span>{index<trace.length-1&&<i/>}</div><div className="trace-event"><button className="trace-toggle" aria-expanded={expanded} onClick={()=>setOpen(expanded?"":item.time)}><span className="trace-title"><span><time>{item.time}</time><b>{item.agent}</b><small>{item.kind}</small></span>{expanded?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</span><p>{item.summary}</p><span className="trace-tags"><Tag tone={escalated?"amber":"green"}>{escalated?"⚠ Escalated":"✓ Autonomous"}</Tag><small>P {item.confidence.toFixed(2)}</small>{item.approver!=="—"&&<small className="approver">Approved by {item.approver}</small>}</span></button>{expanded&&<div className="trace-expanded"><div><small>INPUT SUMMARY</small><span>{item.input}</span></div><div><small>AGENT OUTPUT</small><span>{item.output}</span></div><div><small>POLICY CONTEXT</small><span>{item.policy}</span></div><div><small>GATE & REVIEWER</small><span>{item.gate} · {item.approver}</span></div><p className="evidence-ref"><FileText size={13}/><b>Evidence</b> {item.evidence}<small>PII masked</small></p></div>}</div></article>})}</div></Panel>
 <aside className="trace-aside"><Panel className="policy-card"><div className="policy-heading"><ShieldCheck size={16}/><div><small className="eyebrow">Applied policy</small><b>Autonomy boundary v1.2</b></div></div><div className="policy-values"><div><span>Confidence threshold (τ)</span><b>0.70</b></div><div><span>Maximum risk (Rmax)</span><b>0.60</b></div><div><span>Critical severity risk</span><b className="risk-value">1.00</b></div></div><p>Autonomous only when <b>P ≥ τ</b> and <b>risk ≤ Rmax</b>.</p></Panel><Panel className="integrity-card"><Fingerprint size={18}/><b>Audit trail intact</b><span>Events are written to an append-only log with a correlation ID.</span><small><i className="online-dot"/>No integrity alerts</small></Panel></aside></div>
 </div>}
